import Head from "next/head";

/**
 * Meta component
 * @param {{ title: string, description?: string, imageURL?: string }} props
 * @returns 
 */
export default function Meta({ title, description, imageURL }) {
    return <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{title}</title>
        <meta name="description" content={description || "Generated by create next app"} />
        <link rel="icon" href={imageURL || "/favicon.ico"} />
    </Head>
}