import Head from 'next/head'
import Image from 'next/image'
import helper from '../../resources/undraw_different_love_a-3-rg.svg'

import { useEffect, useState } from "react";

export default function Helper() {
    const [nav, setNav] = useState(false);

    useEffect(() => {
        const menu = document.getElementById("overlay");

        if (nav) {
            menu.classList.add("menu");
        } else if (!nav) {
            menu.classList.remove("menu");
        }
    });
    return (
        <div className="undefined flex flex-col flex-wrap gap-x-0 gap-y-0 w-full justify-center items-center">

            <Head>
                <title>TCS - Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="tcsDark flex flex-col hover:cursor-default w-full">
                <div className="desktop">
                    <div className='fixed top-0 z-50 w-screen h-16 bg-lighter shadow-lg flex justify-start items-center px-3'>
                        <div className="w-8/12 flex flex-col justify-start items-start">
                            <p className="font-extrabold text-white">TCS</p>
                            <p className="text-xs text-violet-500">Helper Application</p>
                        </div>
                        <div className='w-4/12 flex justify-end items-center'>
                            <div className='text-white flex text-base md:text-base lg:text-base p-2 py-1 rounded-lg transition-all duration-700'>
                                <a className='text-center font-bold rounded-xl ml-0.5 hover:text-violet-400' href='/'>
                                    Home
                                </a>
                            </div>
                            <div className='text-white flex text-base md:text-base lg:text-base p-2 py-1 rounded-lg transition-all duration-700'>
                                <a className=' font-bold rounded-xl ml-0.5 hover:text-violet-400' href='/about'>
                                    About
                                </a>
                            </div>
                            <div className='text-white flex text-base md:text-base lg:text-base p-2 py-1 rounded-lg transition-all duration-700'>
                                <a className=' font-bold rounded-xl ml-0.5 hover:text-violet-400' href='/applications'>
                                    Applications
                                </a>
                            </div>
                            <div className='text-white flex text-base md:text-base lg:text-base p-2 py-1 rounded-lg transition-all duration-700'>
                                <a className=' font-bold rounded-xl ml-0.5 hover:text-violet-400' href='/network'>
                                    Network
                                </a>
                            </div>
                            <div className='text-white flex text-base md:text-base lg:text-base p-2 py-1 rounded-lg transition-all duration-700'>
                                <a className=' font-bold rounded-xl ml-0.5 hover:text-violet-400' href='/login'>
                                    Login
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="mobile">
                    <div className='fixed top-0 z-50 w-screen h-16 bg-lighter shadow-lg flex justify-start items-center px-3'>
                        <div className="w-8/12 flex flex-col justify-start items-start">
                            <p className="font-extrabold text-white">TCS</p>
                            <p className="text-xs text-violet-500">Helper Application</p>
                        </div>
                        <div className='w-4/12 flex justify-end items-center'>
                            <div onClick={() => nav ? setNav(false) : setNav(true)} class="burger">
                                <div class="strip burger-strip-2">
                                    <div></div>
                                    <div></div>
                                    <div></div>
                                </div>
                            </div>
                            <div id="overlay">
                                <a className="font-bold rounded-xl ml-0.5 hover:text-violet-400" href="/">Home</a>
                                <a className="font-bold rounded-xl ml-0.5 hover:text-violet-400" href="/about">About</a>
                                <a className="font-bold rounded-xl ml-0.5 hover:text-violet-400" href="/network">Network</a>
                                <a className="font-bold rounded-xl ml-0.5 hover:text-violet-400" href="/applications">Applications</a>
                                <a className="font-bold rounded-xl ml-0.5 hover:text-violet-400" href="/login">Login</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div onClick={() => setNav(false)} className='undefined min-h-screen w-full flex flex-row flex-wrap justify-center items-center content-center'>

                    <div id='mod-app' className='md:py-0 md:px-20 min-h-screen w-full flex flex-row justify-center items-center content-center py-20 lg:py-10 px-10 gap-y-16 flex-wrap'>
                        <div className='undefined h-full w-full aos-init aos-animate'>
                            <div className='flex flex-row dark:text-mtxWhite items-center'>
                                <div className='w-max lg:w-1/2 h-full pr-10'>
                                    <div className='text-white text-4xl md:text-6xl lg:text-6xl font-black leading-10 tracking-tighter lg:tracking-tighter'>
                                        <span className='text-violet-400'> Helper</span> Application.
                                    </div>
                                    <p className='py-5 text-white'>
                                        Thanks for taking interest of being apart of The Coding Society's helper team. Our helper's are the stepping stool to our community.
                                        Welcoming members, consistantly help new members, helping with code, etc. We love our Helper team and we would <b>love</b> for you 
                                        to be apart of it.
                                    </p>
                                    <div className='flex flex-col lg:flex-row gap-y-3 gap-x-5 text-base w-max'>
                                        <a type='button' href='#mod-app' className='cursor-pointer drop-shadow-2xl inline-flex items-center justify-center w-auto px-8 py-4 text-sm font-bold leading-6 text-white bg-indigo-600 border border-transparent rounded-lg md:w-auto hover:bg-indigo-500 transition duration-500 ease-in-out transform hover:-translate-y-1 focus-none'>
                                            Apply Now
                                        </a>
                                    </div>
                                </div>
                                <Image src={helper} />
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}